# Generated by Django 5.2.4 on 2025-07-30 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aloraapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at'], 'verbose_name': 'Booking', 'verbose_name_plural': 'Bookings'},
        ),
        migrations.AlterField(
            model_name='booking',
            name='branch',
            field=models.CharField(max_length=50, verbose_name='Clinic Branch'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(verbose_name='Appointment Date'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='mobile',
            field=models.CharField(max_length=15, verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Patient Name'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.CharField(max_length=50, verbose_name='Service Type'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.CharField(max_length=10, verbose_name='Appointment Time'),
        ),
    ]
